In [144]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [145]:
data = pd.read_csv('csgo_round_snapshots.csv')
data

,time_left,ct_score,t_score,map,bomb_planted,ct_health,t_health,ct_armor,t_armor,ct_money,...,t_grenade_flashbang,ct_grenade_smokegrenade,t_grenade_smokegrenade,ct_grenade_incendiarygrenade,t_grenade_incendiarygrenade,ct_grenade_molotovgrenade,t_grenade_molotovgrenade,ct_grenade_decoygrenade,t_grenade_decoygrenade,round_winner
0,175.00,0.0,0.0,de_dust2,False,500.0,500.0,0.0,0.0,4000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CT
1,156.03,0.0,0.0,de_dust2,False,500.0,500.0,400.0,300.0,600.0,...,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,CT
2,96.03,0.0,0.0,de_dust2,False,391.0,400.0,294.0,200.0,750.0,...,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,CT
3,76.03,0.0,0.0,de_dust2,False,391.0,400.0,294.0,200.0,750.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CT
4,174.97,1.0,0.0,de_dust2,False,500.0,500.0,192.0,0.0,18350.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122405,15.41,11.0,14.0,de_train,True,200.0,242.0,195.0,359.0,100.0,...,2.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,T
122406,174.93,11.0,15.0,de_train,False,500.0,500.0,95.0,175.0,11500.0,...,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,T
122407,114.93,11.0,15.0,de_train,False,500.0,500.0,495.0,475.0,1200.0,...,4.0,3.0,5.0,1.0,0.0,0.0,5.0,0.0,0.0,T
122408,94.93,11.0,15.0,de_train,False,500.0,500.0,495.0,475.0,1200.0,...,5.0,0.0,3.0,0.0,0.0,0.0,4.0,0.0,0.0,T
122409,74.93,11.0,15.0,de_train,False,375.0,479.0,395.0,466.0,1100.0,...,3.0,0.0,2.0,0.0,0.0,0.0,3.0,0.0,0.0,T

### Nedostajuce vrednosti

In [146]:
data.isna().any().any()

False

Primecujemo da u datom skupu podataka ne postoji nijedno polje koje nije popunjeno podacima. Zbog toga nema potrebe za nikakvom obradom podataka u ovom trenutku.

In [147]:
data.describe()

,time_left,ct_score,t_score,ct_health,t_health,ct_armor,t_armor,ct_money,t_money,ct_helmets,...,ct_grenade_flashbang,t_grenade_flashbang,ct_grenade_smokegrenade,t_grenade_smokegrenade,ct_grenade_incendiarygrenade,t_grenade_incendiarygrenade,ct_grenade_molotovgrenade,t_grenade_molotovgrenade,ct_grenade_decoygrenade,t_grenade_decoygrenade
count,122410.000000,122410.000000,122410.000000,122410.000000,122410.000000,122410.000000,122410.000000,122410.000000,122410.000000,122410.000000,...,122410.000000,122410.000000,122410.000000,122410.000000,122410.000000,122410.000000,122410.000000,122410.000000,122410.000000,122410.000000
mean,97.886922,6.709239,6.780435,412.106568,402.714500,314.142121,298.444670,9789.023773,11241.036680,2.053901,...,1.853157,1.858100,1.540814,1.627146,1.001969,0.019819,0.048011,1.352095,0.027694,0.025750
std,54.465238,4.790362,4.823543,132.293290,139.919033,171.029736,174.576545,11215.042286,12162.806759,1.841470,...,1.772791,1.794473,1.737804,1.829147,1.458084,0.143933,0.227669,1.663246,0.169531,0.164162
min,0.010000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,54.920000,3.000000,3.000000,350.000000,322.000000,194.000000,174.000000,1300.000000,1550.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,94.910000,6.000000,6.000000,500.000000,500.000000,377.000000,334.000000,5500.000000,7150.000000,2.000000,...,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
75%,166.917500,10.000000,10.000000,500.000000,500.000000,486.000000,468.000000,14600.000000,18000.000000,4.000000,...,3.000000,3.000000,3.000000,3.000000,2.000000,0.000000,0.000000,2.000000,0.000000,0.000000
max,175.000000,32.000000,33.000000,500.000000,600.000000,500.000000,500.000000,80000.000000,80000.000000,5.000000,...,7.000000,7.000000,6.000000,9.000000,5.000000,3.000000,3.000000,5.000000,3.000000,2.000000

In [148]:
data.drop(index=data.loc[data['t_health'] > 500].index, inplace=True)

for col in data.columns:
    if ('weapon' in col or 'grenade' in col) and data[col].max() > 5:
        print(col, data[col].max())
        data.drop(index=data.loc[data[col] > 5].index, inplace=True)

t_weapon_cz75auto 6.0
t_weapon_glock 9.0
ct_weapon_usps 10.0

In [149]:
data.shape

(122388, 97)

In [150]:
data.describe()

,time_left,ct_score,t_score,ct_health,t_health,ct_armor,t_armor,ct_money,t_money,ct_helmets,...,ct_grenade_flashbang,t_grenade_flashbang,ct_grenade_smokegrenade,t_grenade_smokegrenade,ct_grenade_incendiarygrenade,t_grenade_incendiarygrenade,ct_grenade_molotovgrenade,t_grenade_molotovgrenade,ct_grenade_decoygrenade,t_grenade_decoygrenade
count,122388.000000,122388.000000,122388.000000,122388.000000,122388.000000,122388.000000,122388.000000,122388.000000,122388.000000,122388.000000,...,122388.000000,122388.000000,122388.000000,122388.00000,122388.000000,122388.000000,122388.000000,122388.000000,122388.000000,122388.000000
mean,97.873143,6.708999,6.780126,412.091586,402.697013,314.183727,298.474287,9784.101382,11235.741658,2.054172,...,1.853205,1.858123,1.540886,1.62712,1.002084,0.019822,0.048019,1.352142,0.027699,0.025746
std,54.460431,4.789931,4.823087,132.300165,139.924944,171.004318,174.566840,11204.466220,12152.939687,1.841419,...,1.772741,1.794423,1.737828,1.82903,1.458153,0.143946,0.227688,1.663289,0.169546,0.164153
min,0.010000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,54.920000,3.000000,3.000000,350.000000,322.000000,194.000000,174.000000,1300.000000,1550.000000,0.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,94.910000,6.000000,6.000000,500.000000,500.000000,377.000000,334.000000,5500.000000,7150.000000,2.000000,...,1.000000,1.000000,1.000000,1.00000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
75%,166.910000,10.000000,10.000000,500.000000,500.000000,486.000000,468.000000,14600.000000,18000.000000,4.000000,...,3.000000,3.000000,3.000000,3.00000,2.000000,0.000000,0.000000,2.000000,0.000000,0.000000
max,175.000000,32.000000,33.000000,500.000000,500.000000,500.000000,500.000000,80000.000000,80000.000000,5.000000,...,5.000000,5.000000,5.000000,5.00000,5.000000,3.000000,3.000000,5.000000,3.000000,2.000000

### Podela na ulazne i ciljne podatke
Na kraju svake runde u igrici CS:GO moguca su samo dva ishoda, rundu je pobedila CT strana ili rundu je pobedila T strana. Nase ciljne podatke ce predstavljati upravo krajnji ishod svake runde, koji se nalazi u koloni *round_winner*. Ostatak podataka koristimo kao ulazne podatke kako bi mogli da predvidjamo ko je pobedio rundu.

In [151]:
data.isna().any().any()

False

In [152]:
Y = data['round_winner']
X = data.drop('round_winner', axis=1)
feature_names = X.columns
X.head()

,time_left,ct_score,t_score,map,bomb_planted,ct_health,t_health,ct_armor,t_armor,ct_money,...,ct_grenade_flashbang,t_grenade_flashbang,ct_grenade_smokegrenade,t_grenade_smokegrenade,ct_grenade_incendiarygrenade,t_grenade_incendiarygrenade,ct_grenade_molotovgrenade,t_grenade_molotovgrenade,ct_grenade_decoygrenade,t_grenade_decoygrenade
0,175.00,0.0,0.0,de_dust2,False,500.0,500.0,0.0,0.0,4000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,156.03,0.0,0.0,de_dust2,False,500.0,500.0,400.0,300.0,600.0,...,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
2,96.03,0.0,0.0,de_dust2,False,391.0,400.0,294.0,200.0,750.0,...,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
3,76.03,0.0,0.0,de_dust2,False,391.0,400.0,294.0,200.0,750.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,174.97,1.0,0.0,de_dust2,False,500.0,500.0,192.0,0.0,18350.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [153]:
X.isna().any().any()

False

In [154]:
X.head()

,time_left,ct_score,t_score,map,bomb_planted,ct_health,t_health,ct_armor,t_armor,ct_money,...,ct_grenade_flashbang,t_grenade_flashbang,ct_grenade_smokegrenade,t_grenade_smokegrenade,ct_grenade_incendiarygrenade,t_grenade_incendiarygrenade,ct_grenade_molotovgrenade,t_grenade_molotovgrenade,ct_grenade_decoygrenade,t_grenade_decoygrenade
0,175.00,0.0,0.0,de_dust2,False,500.0,500.0,0.0,0.0,4000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,156.03,0.0,0.0,de_dust2,False,500.0,500.0,400.0,300.0,600.0,...,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
2,96.03,0.0,0.0,de_dust2,False,391.0,400.0,294.0,200.0,750.0,...,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
3,76.03,0.0,0.0,de_dust2,False,391.0,400.0,294.0,200.0,750.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,174.97,1.0,0.0,de_dust2,False,500.0,500.0,192.0,0.0,18350.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [155]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 122388 entries, 0 to 122409
Data columns (total 96 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   time_left                     122388 non-null  float64
 1   ct_score                      122388 non-null  float64
 2   t_score                       122388 non-null  float64
 3   map                           122388 non-null  object
 4   bomb_planted                  122388 non-null  bool
 5   ct_health                     122388 non-null  float64
 6   t_health                      122388 non-null  float64
 7   ct_armor                      122388 non-null  float64
 8   t_armor                       122388 non-null  float64
 9   ct_money                      122388 non-null  float64
 10  t_money                       122388 non-null  float64
 11  ct_helmets                    122388 non-null  float64
 12  t_helmets                     122388 non-null  float64
 13  ct_defuse_kits                122388 non-null  float64
 14  ct_players_alive              122388 non-null  float64
 15  t_players_alive               122388 non-null  float64
 16  ct_weapon_ak47                122388 non-null  float64
 17  t_weapon_ak47                 122388 non-null  float64
 18  ct_weapon_aug                 122388 non-null  float64
 19  t_weapon_aug                  122388 non-null  float64
 20  ct_weapon_awp                 122388 non-null  float64
 21  t_weapon_awp                  122388 non-null  float64
 22  ct_weapon_bizon               122388 non-null  float64
 23  t_weapon_bizon                122388 non-null  float64
 24  ct_weapon_cz75auto            122388 non-null  float64
 25  t_weapon_cz75auto             122388 non-null  float64
 26  ct_weapon_elite               122388 non-null  float64
 27  t_weapon_elite                122388 non-null  float64
 28  ct_weapon_famas               122388 non-null  float64
 29  t_weapon_famas                122388 non-null  float64
 30  ct_weapon_g3sg1               122388 non-null  float64
 31  t_weapon_g3sg1                122388 non-null  float64
 32  ct_weapon_galilar             122388 non-null  float64
 33  t_weapon_galilar              122388 non-null  float64
 34  ct_weapon_glock               122388 non-null  float64
 35  t_weapon_glock                122388 non-null  float64
 36  ct_weapon_m249                122388 non-null  float64
 37  t_weapon_m249                 122388 non-null  float64
 38  ct_weapon_m4a1s               122388 non-null  float64
 39  t_weapon_m4a1s                122388 non-null  float64
 40  ct_weapon_m4a4                122388 non-null  float64
 41  t_weapon_m4a4                 122388 non-null  float64
 42  ct_weapon_mac10               122388 non-null  float64
 43  t_weapon_mac10                122388 non-null  float64
 44  ct_weapon_mag7                122388 non-null  float64
 45  t_weapon_mag7                 122388 non-null  float64
 46  ct_weapon_mp5sd               122388 non-null  float64
 47  t_weapon_mp5sd                122388 non-null  float64
 48  ct_weapon_mp7                 122388 non-null  float64
 49  t_weapon_mp7                  122388 non-null  float64
 50  ct_weapon_mp9                 122388 non-null  float64
 51  t_weapon_mp9                  122388 non-null  float64
 52  ct_weapon_negev               122388 non-null  float64
 53  t_weapon_negev                122388 non-null  float64
 54  ct_weapon_nova                122388 non-null  float64
 55  t_weapon_nova                 122388 non-null  float64
 56  ct_weapon_p90                 122388 non-null  float64
 57  t_weapon_p90                  122388 non-null  float64
 58  ct_weapon_r8revolver          122388 non-null  float64
 59  t_weapon_r8revolver           122388 non-null  float64
 60  ct_weapon_sawedoff            122388 non-null  float64
 61  t_weapon_sawedoff             122388 non-null  float64
 62  ct_weapon_scar20              122388 non-null  float64
 63  t_weapon_scar20               122388 non-null  float64
 64  ct_weapon_sg553               122388 non-null  float64
 65  t_weapon_sg553                122388 non-null  float64
 66  ct_weapon_ssg08               122388 non-null  float64
 67  t_weapon_ssg08                122388 non-null  float64
 68  ct_weapon_ump45               122388 non-null  float64
 69  t_weapon_ump45                122388 non-null  float64
 70  ct_weapon_xm1014              122388 non-null  float64
 71  t_weapon_xm1014               122388 non-null  float64
 72  ct_weapon_deagle              122388 non-null  float64
 73  t_weapon_deagle               122388 non-null  float64
 74  ct_weapon_fiveseven           122388 non-null  float64
 75  t_weapon_fiveseven            122388 non-null  float64
 76  ct_weapon_usps                122388 non-null  float64
 77  t_weapon_usps                 122388 non-null  float64
 78  ct_weapon_p250                122388 non-null  float64
 79  t_weapon_p250                 122388 non-null  float64
 80  ct_weapon_p2000               122388 non-null  float64
 81  t_weapon_p2000                122388 non-null  float64
 82  ct_weapon_tec9                122388 non-null  float64
 83  t_weapon_tec9                 122388 non-null  float64
 84  ct_grenade_hegrenade          122388 non-null  float64
 85  t_grenade_hegrenade           122388 non-null  float64
 86  ct_grenade_flashbang          122388 non-null  float64
 87  t_grenade_flashbang           122388 non-null  float64
 88  ct_grenade_smokegrenade       122388 non-null  float64
 89  t_grenade_smokegrenade        122388 non-null  float64
 90  ct_grenade_incendiarygrenade  122388 non-null  float64
 91  t_grenade_incendiarygrenade   122388 non-null  float64
 92  ct_grenade_molotovgrenade     122388 non-null  float64
 93  t_grenade_molotovgrenade      122388 non-null  float64
 94  ct_grenade_decoygrenade       122388 non-null  float64
 95  t_grenade_decoygrenade        122388 non-null  float64
dtypes: bool(1), float64(94), object(1)
memory usage: 89.8+ MB

In [156]:
Y.unique()

array(['CT', 'T'], dtype=object)

In [157]:
Y.replace('CT', 0, inplace=True)
Y.replace('T', 1, inplace=True)

In [158]:
Y.unique()

array([0, 1], dtype=int64)

In [159]:
maps = X['map'].unique()

In [160]:
maps_dict = {}
i = 0

for map in maps:
    maps_dict[map] = i
    i += 1

X['map'].replace(maps_dict, inplace=True)
X

,time_left,ct_score,t_score,map,bomb_planted,ct_health,t_health,ct_armor,t_armor,ct_money,...,ct_grenade_flashbang,t_grenade_flashbang,ct_grenade_smokegrenade,t_grenade_smokegrenade,ct_grenade_incendiarygrenade,t_grenade_incendiarygrenade,ct_grenade_molotovgrenade,t_grenade_molotovgrenade,ct_grenade_decoygrenade,t_grenade_decoygrenade
0,175.00,0.0,0.0,0,False,500.0,500.0,0.0,0.0,4000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,156.03,0.0,0.0,0,False,500.0,500.0,400.0,300.0,600.0,...,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
2,96.03,0.0,0.0,0,False,391.0,400.0,294.0,200.0,750.0,...,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
3,76.03,0.0,0.0,0,False,391.0,400.0,294.0,200.0,750.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,174.97,1.0,0.0,0,False,500.0,500.0,192.0,0.0,18350.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122405,15.41,11.0,14.0,6,True,200.0,242.0,195.0,359.0,100.0,...,1.0,2.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
122406,174.93,11.0,15.0,6,False,500.0,500.0,95.0,175.0,11500.0,...,1.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
122407,114.93,11.0,15.0,6,False,500.0,500.0,495.0,475.0,1200.0,...,4.0,4.0,3.0,5.0,1.0,0.0,0.0,5.0,0.0,0.0
122408,94.93,11.0,15.0,6,False,500.0,500.0,495.0,475.0,1200.0,...,1.0,5.0,0.0,3.0,0.0,0.0,0.0,4.0,0.0,0.0
122409,74.93,11.0,15.0,6,False,375.0,479.0,395.0,466.0,1100.0,...,0.0,3.0,0.0,2.0,0.0,0.0,0.0,3.0,0.0,0.0

In [161]:
X['bomb_planted'].replace({True: 1, False: 0}, inplace=True)
X

,time_left,ct_score,t_score,map,bomb_planted,ct_health,t_health,ct_armor,t_armor,ct_money,...,ct_grenade_flashbang,t_grenade_flashbang,ct_grenade_smokegrenade,t_grenade_smokegrenade,ct_grenade_incendiarygrenade,t_grenade_incendiarygrenade,ct_grenade_molotovgrenade,t_grenade_molotovgrenade,ct_grenade_decoygrenade,t_grenade_decoygrenade
0,175.00,0.0,0.0,0,0,500.0,500.0,0.0,0.0,4000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,156.03,0.0,0.0,0,0,500.0,500.0,400.0,300.0,600.0,...,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
2,96.03,0.0,0.0,0,0,391.0,400.0,294.0,200.0,750.0,...,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
3,76.03,0.0,0.0,0,0,391.0,400.0,294.0,200.0,750.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,174.97,1.0,0.0,0,0,500.0,500.0,192.0,0.0,18350.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122405,15.41,11.0,14.0,6,1,200.0,242.0,195.0,359.0,100.0,...,1.0,2.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
122406,174.93,11.0,15.0,6,0,500.0,500.0,95.0,175.0,11500.0,...,1.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
122407,114.93,11.0,15.0,6,0,500.0,500.0,495.0,475.0,1200.0,...,4.0,4.0,3.0,5.0,1.0,0.0,0.0,5.0,0.0,0.0
122408,94.93,11.0,15.0,6,0,500.0,500.0,495.0,475.0,1200.0,...,1.0,5.0,0.0,3.0,0.0,0.0,0.0,4.0,0.0,0.0
122409,74.93,11.0,15.0,6,0,375.0,479.0,395.0,466.0,1100.0,...,0.0,3.0,0.0,2.0,0.0,0.0,0.0,3.0,0.0,0.0

In [162]:
# def minmax_scaler(data):
#     return (data - min(data)) / (max(data) - min(data))

In [163]:
# for col in X.columns:
#     X[col] = minmax_scaler(X[col])
# X.info()

In [164]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_scaled = scaler.fit_transform(X)
X = pd.DataFrame(data=X_scaled, columns=X.columns)

In [165]:
X.describe()

,time_left,ct_score,t_score,map,bomb_planted,ct_health,t_health,ct_armor,t_armor,ct_money,...,ct_grenade_flashbang,t_grenade_flashbang,ct_grenade_smokegrenade,t_grenade_smokegrenade,ct_grenade_incendiarygrenade,t_grenade_incendiarygrenade,ct_grenade_molotovgrenade,t_grenade_molotovgrenade,ct_grenade_decoygrenade,t_grenade_decoygrenade
count,122388.000000,122388.000000,122388.000000,122388.000000,122388.000000,122388.000000,122388.000000,122388.000000,122388.000000,122388.000000,...,122388.000000,122388.000000,122388.000000,122388.000000,122388.000000,122388.000000,122388.000000,122388.000000,122388.000000,122388.000000
mean,0.559250,0.209656,0.205458,0.375841,0.111808,0.824183,0.805394,0.628367,0.596949,0.122301,...,0.370641,0.371625,0.308177,0.325424,0.200417,0.006607,0.016006,0.270428,0.009233,0.012873
std,0.311220,0.149685,0.146154,0.276421,0.315132,0.264600,0.279850,0.342009,0.349134,0.140056,...,0.354548,0.358885,0.347566,0.365806,0.291631,0.047982,0.075896,0.332658,0.056515,0.082077
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.313789,0.093750,0.090909,0.142857,0.000000,0.700000,0.644000,0.388000,0.348000,0.016250,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.542317,0.187500,0.181818,0.428571,0.000000,1.000000,1.000000,0.754000,0.668000,0.068750,...,0.200000,0.200000,0.200000,0.200000,0.000000,0.000000,0.000000,0.200000,0.000000,0.000000
75%,0.953769,0.312500,0.303030,0.571429,0.000000,1.000000,1.000000,0.972000,0.936000,0.182500,...,0.600000,0.600000,0.600000,0.600000,0.400000,0.000000,0.000000,0.400000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [166]:
from joblib import dump

In [167]:
dump((X, Y), 'data.joblib')

['data.joblib']